import { createFileRoute } from "@tanstack/react-router";
import JSZip from "jszip";
import { Download } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { extractInvoice } from "@/lib/peppol/extract";
import { t } from "@/lib/peppol/i18n";
import { extractPdfText } from "@/lib/peppol/pdf";
import { usePrefs } from "@/lib/peppol/prefs";
import { consumeBulkQuota, fetchQuota } from "@/lib/peppol/quota";
import { saveConversion } from "@/lib/peppol/conversions";
import { validateInvoice } from "@/lib/peppol/validate";
import { buildUblXml, suggestedFilename } from "@/lib/peppol/xml";
import { downloadBlob } from "@/lib/utils";
import { useAuth } from "@/lib/auth/local";

export const Route=createFileRoute("/bulk")({component:BulkPage});
type Row={name:string;status:string;xml?:string;invoice?:string};
const MAX_ZIP_BYTES=50*1024*1024;
const MAX_ZIP_ENTRIES=100;
const MAX_EXTRACTED_BYTES=100*1024*1024;

async function expandInputFiles(files:File[]):Promise<File[]>{const result:File[]=[];for(const file of files){if(!/\.zip$/i.test(file.name)){result.push(file);continue;}if(file.size>MAX_ZIP_BYTES){result.push(new File([],file.name,{type:"application/zip"}));continue;}try{const archive=await JSZip.loadAsync(file);const allEntries=Object.values(archive.files);if(allEntries.length>MAX_ZIP_ENTRIES){result.push(new File([],file.name,{type:"application/zip"}));continue;}let extractedBytes=0;let rejectedUnsafe=false;for(const entry of allEntries){if(entry.dir||!/\.pdf$/i.test(entry.name))continue;const originalName=(entry as typeof entry & {unsafeOriginalName?:string}).unsafeOriginalName??entry.name;if(originalName.split(/[\\/]/).some(part=>part==="..")){rejectedUnsafe=true;continue;}const declaredSize=Number((entry as typeof entry & {_data?:{uncompressedSize?:number}})._data?.uncompressedSize??0);if(declaredSize>20*1024*1024||extractedBytes+declaredSize>MAX_EXTRACTED_BYTES){rejectedUnsafe=true;continue;}const blob=await entry.async("blob");if(blob.size>20*1024*1024||extractedBytes+blob.size>MAX_EXTRACTED_BYTES){rejectedUnsafe=true;continue;}extractedBytes+=blob.size;const name=entry.name.split(/[\\/]/).pop()||"invoice.pdf";result.push(new File([blob],name,{type:"application/pdf"}));}if(rejectedUnsafe&&!result.some((item)=>item.name===file.name))result.push(new File([],file.name,{type:"application/zip"}));if(!allEntries.some((entry)=>!entry.dir&&/\.pdf$/i.test(entry.name)))result.push(new File([],file.name,{type:"application/zip"}));}catch{result.push(new File([],file.name,{type:"application/zip"}));}}return result;}
function csvCell(value:string){return `"${value.replaceAll('"','""')}"`;}
function uniqueFilename(filename:string,used:Set<string>){const dot=filename.lastIndexOf(".");const stem=dot>0?filename.slice(0,dot):filename;const ext=dot>0?filename.slice(dot):"";let candidate=filename;let index=2;while(used.has(candidate)){candidate=`${stem}-${index}${ext}`;index+=1;}used.add(candidate);return candidate;}
function looksLikeInvoice(text:string):boolean{const invoiceId=/\b(?:invoice|factuur|facture)\s*(?:number|no\.?|#|n[°oº]|num[eé]ro)\s*[:#./-]?\s*[A-Z0-9][A-Z0-9/_-]{2,}\b/i.test(text)||/\bINV[-/]\d{2,4}[-/]?\d{2,}\b/i.test(text);const issueDate=/\b(?:invoice\s*date|factuurdatum|issue\s*date|date\s*(?:de\s*)?facture)\s*[:.]?\s*\d{1,2}[./-]\d{1,2}[./-]\d{4}\b/i.test(text);const supporting=[/\b(vat|btw|tva)\b/i.test(text),/\b(total|totaal|montant)\b/i.test(text),/\b(supplier|seller|leverancier|fournisseur|customer|buyer|klant|client|bill to)\b/i.test(text),/\b(iban|eur|€)\b/i.test(text)].filter(Boolean).length;return (invoiceId||issueDate)&&supporting>=2&&/\d/.test(text);}

function BulkPage(){const lang=usePrefs(s=>s.lang);const user=useAuth(s=>s.user);const [rows,setRows]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [quota,setQuota]=useState({used:0,limit:0,remaining:0});useEffect(()=>{if(user)void fetchQuota().then(setQuota).catch(()=>undefined);},[user]);
 async function run(inputFiles:File[]){if(!user)return;setBusy(true);const files=await expandInputFiles(inputFiles);const next:Row[]=[];let bulkReserved=false;let conversionRemaining=quota.remaining;for(const file of files){if(/\.zip$/i.test(file.name)){next.push({name:file.name,status:file.size===0?"FAIL — ZIP rejected (invalid, oversized, unsafe, or empty).":"FAIL — ZIP could not be opened or contains no usable PDF files."});continue;}if(conversionRemaining<=0){next.push({name:file.name,status:t(lang,"quota_full")});continue;}const extracted=await extractPdfText(file);if(!extracted.success){next.push({name:file.name,status:`FAIL — ${extracted.error?.code??"PDF_READ"}: ${extracted.error?.userMessage??"Could not read PDF."}`});continue;}if(!looksLikeInvoice(extracted.fullText)){next.push({name:file.name,status:"FAIL — NOT AN INVOICE: the PDF does not contain enough invoice evidence."});continue;}const data=extractInvoice(extracted.fullText);const result=validateInvoice(data);if(!result.ok){const blocking=result.issues.filter((issue)=>issue.severity==="error");const codes=blocking.slice(0,4).map((issue)=>issue.code).join(", ");const suffix=blocking.length>4?", …":"";next.push({name:file.name,status:`FAIL — ${blocking.length} BLOCKING ${blocking.length===1?"CHECK":"CHECKS"}${codes?` (${codes}${suffix})`:""}`});continue;}if(!bulkReserved){try{await consumeBulkQuota();bulkReserved=true;}catch(e){next.push({name:file.name,status:e instanceof Error?e.message:"Bulk conversion is not available on this plan."});break;}}const xml=buildUblXml(data);const invoice=suggestedFilename(data);try{await saveConversion(user.id,{invoice_id:data.invoiceNumber.value||"untitled",supplier:data.supplierName.value,customer:data.customerName.value,total:data.payableAmount.value,currency:data.currency.value,status:"ok",issue_count:result.issues.length});conversionRemaining-=1;next.push({name:file.name,status:"PASS — READY",xml,invoice});}catch(e){next.push({name:file.name,status:e instanceof Error?e.message:t(lang,"quota_full")});break;}}
 setRows(next);void fetchQuota().then(setQuota).catch(()=>undefined);setBusy(false);}
 async function zipAll(){const zip=new JSZip();const summary=["file,status,xml"];const used=new Set<string>();for(const row of rows){const output=row.xml&&row.invoice?uniqueFilename(row.invoice,used):"";if(row.xml&&output)zip.file(output,row.xml);summary.push([row.name,row.status,output].map(csvCell).join(","));}zip.file("summary.csv",summary.join("\n"));downloadBlob("peppol-bulk.zip",await zip.generateAsync({type:"blob"}));}
 return <main className="mx-auto max-w-4xl px-4 py-10"><h1 className="font-display text-3xl tracking-tight">{t(lang,"bulk_title")}</h1><p className="mt-2 text-muted">{t(lang,"bulk_sub")}</p>{!user?<p className="mt-4 text-sm text-danger">Sign in to use bulk conversion.</p>:<><p className="mt-2 text-sm text-muted">{t(lang,"quota",{used:quota.used,limit:quota.limit})}</p><label className="mt-6 grid min-h-40 cursor-pointer place-items-center rounded-2xl border border-dashed border-border bg-elevated p-6"><input type="file" accept="application/pdf,.zip,application/zip" multiple className="hidden" disabled={busy} onChange={e=>{const files=[...(e.target.files??[])];if(files.length)void run(files);}}/><p className="text-sm">{busy?t(lang,"extracting",{page:0,total:0}):t(lang,"bulk_run")}</p></label>{rows.length?<div className="mt-6 overflow-auto rounded-xl border border-border"><table className="w-full text-sm"><thead className="bg-surface text-left text-muted"><tr><th className="px-3 py-2">PDF</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.name}-${i}`} className="border-t border-border"><td className="px-3 py-2">{r.name}</td><td className={r.status.startsWith("PASS")?"px-3 py-2 text-accent":"px-3 py-2 text-danger"}>{r.status}</td></tr>)}</tbody></table></div>:null}<div className="mt-4 flex flex-wrap gap-2"><Button type="button" disabled={!rows.some(r=>r.xml)} onClick={()=>void zipAll()}><Download className="size-4"/>{t(lang,"bulk_download")}</Button><Button type="button" variant="outline" onClick={()=>{window.location.href="/pricing";}}>{t(lang,"upgrade")}</Button></div></>}</main>;
}
