import { Link, createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth/local";
import { listConversions, type ConversionRow } from "@/lib/peppol/conversions";
import { t } from "@/lib/peppol/i18n";
import { usePrefs } from "@/lib/peppol/prefs";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/dashboard")({component:Dashboard});
function Dashboard(){const lang=usePrefs(s=>s.lang);const {user,hydrated}=useAuth();const [rows,setRows]=useState<ConversionRow[]>([]);useEffect(()=>{if(user)setRows(listConversions(user.id));},[user]);if(!hydrated)return <main className="mx-auto max-w-5xl px-4 py-12"><div className="h-40 animate-pulse rounded-xl bg-surface"/></main>;if(!user)return <main className="mx-auto max-w-md px-4 py-20 text-center"><h1 className="font-display text-3xl">{t(lang,"login_title")}</h1><p className="mt-2 text-muted">{t(lang,"login_sub")}</p><Button asChild className="mt-6"><Link to="/login">{t(lang,"nav_login")}</Link></Button></main>;return <main className="mx-auto max-w-5xl px-4 py-12"><h1 className="font-display text-3xl tracking-tight">{t(lang,"dash_title")}</h1><p className="mt-2 text-muted">{t(lang,"dash_sub")}</p>{!rows.length?<div className="mt-8 rounded-2xl border border-border bg-elevated p-8"><p className="text-muted">{t(lang,"dash_empty")}</p><Button asChild className="mt-4"><Link to="/converter">{t(lang,"hero_cta")}</Link></Button></div>:<div className="mt-8 overflow-auto rounded-xl border border-border"><table className="w-full min-w-[640px] text-sm"><thead className="bg-surface text-left text-muted"><tr><th className="px-3 py-2">Invoice</th><th className="px-3 py-2">{t(lang,"supplier")}</th><th className="px-3 py-2">{t(lang,"customer")}</th><th className="px-3 py-2">{t(lang,"f_payable")}</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-border"><td className="px-3 py-2 font-mono text-xs">{r.invoice_id}</td><td className="px-3 py-2">{r.supplier}</td><td className="px-3 py-2">{r.customer}</td><td className="px-3 py-2">{r.total} {r.currency}</td><td className="px-3 py-2">{r.status==="ok"?t(lang,"status_ok"):t(lang,"status_issues")}</td></tr>)}</tbody></table></div>}</main>}
