import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/lib/auth/local";
import { t } from "@/lib/peppol/i18n";
import { usePrefs } from "@/lib/peppol/prefs";
export const Route = createFileRoute("/login")({ component: Login });
function Login(){const lang=usePrefs(s=>s.lang);const navigate=useNavigate();const {signIn,signUp}=useAuth();const [mode,setMode]=useState<"in"|"up">("in");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{mode==="up"?await signUp(name,email,password):await signIn(email,password);await navigate({to:"/dashboard"});}catch(e){setError(e instanceof Error?e.message:"Authentication failed");}finally{setBusy(false);}}return <main className="mx-auto grid min-h-[70vh] max-w-md place-items-center px-4 py-12"><div className="w-full rounded-2xl border border-border bg-elevated p-6"><h1 className="font-display text-3xl tracking-tight">{t(lang,"login_title")}</h1><p className="mt-2 text-sm text-muted">{t(lang,"login_sub")}</p><form className="mt-6 grid gap-3" onSubmit={submit}>{mode==="up"&&<label className="grid gap-1 text-sm">{t(lang,"login_name")}<Input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label className="grid gap-1 text-sm">{t(lang,"login_email")}<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="grid gap-1 text-sm">{t(lang,"login_password")}<Input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="text-sm text-danger">{error}</p>}<Button disabled={busy}>{mode==="up"?t(lang,"signup_with_email"):t(lang,"login_with_email")}</Button><button type="button" className="text-sm text-muted underline-offset-4 hover:underline" onClick={()=>setMode(mode==="up"?"in":"up")}>{mode==="up"?t(lang,"login_with_email"):t(lang,"signup_with_email")}</button></form><p className="mt-5 text-xs leading-relaxed text-subtle">Your account is stored locally in this browser in this Vercel-ready edition. For production multi-device accounts, connect a database/auth provider.</p></div></main>}
