import { nodeRequestToWebRequest } from "../usage.js";
import { getDb } from "../_lib/db.js";
import { getSessionUser, requireSameOrigin, securityEvent } from "../_lib/auth.js";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
type VercelRequest={method?:string;url?:string;headers:Record<string,string|string[]|undefined>;body?:unknown;[key:string]:unknown};
type VercelResponse={statusCode?:number;setHeader(name:string,value:string|string[]):VercelResponse;end(body?:string):void};
async function sendWebResponse(response:Response,res:VercelResponse):Promise<void>{res.statusCode=response.status;response.headers.forEach((value,name)=>res.setHeader(name,value));res.end(await response.text());}
async function handleAdminUsersRequest(request:Request):Promise<Response>{const user=await getSessionUser(request);if(!user)return json({error:"Authentication required."},401);if(user.role!=="admin")return json({error:"Forbidden."},403);const sql=getDb();if(request.method==="GET"){const rows=await sql<any[]>`SELECT u.id,u.email,u.name,u.role,u.plan_id,u.email_verified_at,u.disabled_at,u.created_at,s.status AS subscription_status FROM users u LEFT JOIN LATERAL (SELECT status FROM subscriptions WHERE user_id=u.id ORDER BY created_at DESC LIMIT 1) s ON true ORDER BY u.created_at DESC LIMIT 500`;return json({users:rows});}if(request.method!=="PATCH")return json({error:"Method not allowed."},405);requireSameOrigin(request);const input=await request.json().catch(()=>null) as {userId?:unknown;role?:unknown;planId?:unknown;disabled?:unknown}|null;if(typeof input?.userId!=="string")return json({error:"userId is required."},400);if(input.userId===user.id&&input.disabled===true)return json({error:"An administrator cannot disable their own current account."},400);if(input.role!==undefined&&input.role!=="user"&&input.role!=="admin")return json({error:"Invalid role."},400);if(input.planId!==undefined&&!["free","paid","business","admin"].includes(String(input.planId)))return json({error:"Invalid plan."},400);const role=input.role===undefined?null:String(input.role);const planId=input.planId===undefined?null:String(input.planId);const disabled=input.disabled===undefined?null:Boolean(input.disabled);const rows=await sql<any[]>`UPDATE users SET role=COALESCE(${role},role), plan_id=COALESCE(${planId},plan_id), disabled_at=CASE WHEN ${disabled} IS NULL THEN disabled_at WHEN ${disabled}=true THEN COALESCE(disabled_at,now()) ELSE NULL END, updated_at=now() WHERE id=${input.userId} RETURNING id,email,name,role,plan_id,email_verified_at,disabled_at`;if(!rows[0])return json({error:"User not found."},404);if(disabled===true)await sql`UPDATE sessions SET revoked_at=now() WHERE user_id=${input.userId} AND revoked_at IS NULL`;await securityEvent(request,"admin_user_updated",user.id,{targetUserId:input.userId,role,planId,disabled});return json({user:rows[0]});}
export default async function handler(request:VercelRequest,response:VercelResponse):Promise<void>{await sendWebResponse(await handleAdminUsersRequest(await nodeRequestToWebRequest(request)),response);}
