import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const quotaSource = readFileSync("src/lib/peppol/quota.ts", "utf8");
const converterSource = readFileSync("src/routes/converter.tsx", "utf8");
const bulkSource = readFileSync("src/routes/bulk.tsx", "utf8");
const conversionApi = readFileSync("api/conversions.ts", "utf8");
const conversionsSource = readFileSync("src/lib/peppol/conversions.ts", "utf8");
const dashboardSource = readFileSync("src/routes/dashboard.tsx", "utf8");
const usageApi = readFileSync("api/usage.ts", "utf8");
const pricingSource = readFileSync("src/lib/peppol/pricing.ts", "utf8");
const pricingPageSource = readFileSync("src/routes/pricing.tsx", "utf8");
const privacySource = readFileSync("src/routes/privacy.tsx", "utf8");
const entitlementMigration = readFileSync("migrations/003_align_plan_entitlements.sql", "utf8");

assert.match(quotaSource, /ANONYMOUS_TRIAL_LIMIT = 3/, "Anonymous trial target must be explicit and local-only");
assert.match(quotaSource, /localStorage/, "Anonymous quota must remain a soft browser-local mechanism");
assert.match(converterSource, /consumeAnonymousQuota\(\)/, "Anonymous successful downloads must consume the local trial quota");
assert.match(converterSource, /saveConversion\([\s\S]*?issue_count:\s*result\.issues\.length/, "Authenticated conversion history must persist the actual validation issue count");
assert.match(converterSource, /if\s*\(\s*conversionSaved\s*\)/, "Repeated downloads must not create duplicate conversion records");
assert.match(conversionApi, /WITH quota AS/, "Server conversion quota and history must be committed atomically in one SQL statement");
assert.match(conversionApi, /input\.kind !== \"conversion\"/, "Conversion API must accept only the single-conversion entitlement path");
assert.doesNotMatch(conversionApi, /kind === \"bulk\"/, "Conversion API must not provide a quota-bypassing bulk record path");
assert.match(conversionApi, /request\.method === \"DELETE\"/, "Conversion API must expose an authenticated deletion path");
assert.match(conversionApi, /DELETE FROM conversions WHERE user_id = \$\{user\.id\}/, "History deletion must be scoped to the authenticated user");
assert.match(conversionApi, /requireSameOrigin\(request\)/, "State-changing conversion deletion must require same-origin protection");
assert.match(conversionApi, /conversion_history_deleted/, "History deletion must emit a security audit event");
assert.match(conversionsSource, /deleteConversionHistory/, "Client conversion library must expose history deletion");
assert.match(dashboardSource, /deleteConversionHistory\(\)/, "Dashboard must invoke the authenticated history deletion path");
assert.match(dashboardSource, /Delete history/, "Dashboard must expose the deletion control");
assert.match(dashboardSource, /cannot be undone/, "Deletion control must warn that history deletion is irreversible");
assert.match(usageApi, /plan\?\.plan_id===\"free\"/, "Bulk entitlement must be enforced server-side for Free accounts");
assert.match(usageApi, /bulk_used=usage_quota\.bulk_used\+1/, "Bulk job usage must be atomic");
assert.match(bulkSource, /consumeBulkQuota\(\)/, "Bulk conversion must reserve a bulk job entitlement");
assert.match(bulkSource, /bulkReserved/, "One bulk upload must consume one bulk job entitlement");
assert.match(bulkSource, /saveConversion\(/, "Each successful bulk PDF must be persisted to history");
assert.doesNotMatch(bulkSource, /saveConversion\([^\n]+\"bulk\"\)/, "Bulk PDFs must consume conversion allowance, not one bulk slot each");
assert.match(bulkSource, /MAX_ZIP_BYTES=50\*1024\*1024/, "Bulk ZIP size must be bounded");
assert.match(bulkSource, /MAX_ZIP_ENTRIES=100/, "Bulk ZIP entry count must be bounded");
assert.match(bulkSource, /MAX_EXTRACTED_BYTES=100\*1024\*1024/, "Bulk extracted size must be bounded");
assert.match(bulkSource, /unsafeOriginalName/, "ZIP traversal entries must be inspected explicitly");
assert.match(bulkSource, /uniqueFilename/, "Duplicate output filenames must not overwrite each other");
assert.match(pricingSource, /id: \"free\"/, "Free tier must remain present");
assert.match(pricingSource, /id: \"pro\"/, "Pro tier must be represented by the actual product tier");
assert.match(pricingSource, /id: \"business\"/, "Business tier must be represented by the actual product tier");
assert.doesNotMatch(pricingSource, /price: (19|49|99)/, "Unfinalized paid prices must not be published");
assert.match(pricingPageSource, /tier\.localized\[lang\]/, "Pricing tier content must follow the selected language");
assert.match(pricingPageSource, /notice\[lang\]/, "Pricing notice must follow the selected language");
assert.match(pricingPageSource, /pricing_mo/, "Pricing page must use the localized monthly label");
assert.match(pricingPageSource, /annualPrice/, "Pricing page must expose the annual price while billing is still disabled");
assert.match(pricingPageSource, /billingPeriod: \"Billing period\"/, "Pricing billing-period control must have an accessible label");
assert.match(pricingPageSource, /billingPeriod: \"Période de facturation\"/, "French pricing billing-period control must be localized");
assert.match(pricingPageSource, /billingPeriod: \"Facturatieperiode\"/, "Dutch pricing billing-period control must be localized");
assert.match(pricingPageSource, /saveYear: \"Save\"/, "Annual savings copy must explicitly identify the savings amount");
assert.match(pricingPageSource, /saveYear: \"Économisez\"/, "French annual savings copy must explicitly identify the savings amount");
assert.match(pricingPageSource, /saveYear: \"Bespaar\"/, "Dutch annual savings copy must explicitly identify the savings amount");
assert.match(pricingPageSource, /annualSaving\}\s*\/\s*\{copy\[lang\]\.year\}/, "Annual savings must be expressed with an explicit annual unit");
assert.match(pricingSource, /fr: \{ name: \"Gratuit\"/, "French pricing tier labels must be defined");
assert.match(pricingSource, /nl: \{ name: \"Gratis\"/, "Dutch pricing tier labels must be defined");
assert.match(entitlementMigration, /monthly_conversion_limit = 5, monthly_bulk_limit = 0/, "Free must have 5 document units and no bulk allowance");
assert.match(entitlementMigration, /monthly_conversion_limit = 100, monthly_bulk_limit = 500/, "Legacy paid plan must match approved Pro entitlements");
assert.match(entitlementMigration, /monthly_conversion_limit = 1000, monthly_bulk_limit = 10000/, "Business entitlements must match approved pricing");
assert.match(privacySource, /Google or with email and password/, "Privacy page must describe current authentication accurately");
assert.match(privacySource, /Microsoft and itsme/, "Future sign-in providers must be clearly described as planned");
assert.match(privacySource, /browser.*PDF|PDF.*browser/i, "Privacy page must describe browser-side PDF processing");
assert.match(privacySource, /does\s+not\s+store the uploaded PDF or generated XML body/, "Privacy page must describe current storage behavior even when JSX wraps the sentence");
assert.match(privacySource, /Vercel/, "Privacy page must identify current hosting infrastructure");
assert.match(privacySource, /Neon PostgreSQL/, "Privacy page must identify current database infrastructure");
assert.match(privacySource, /Signed-in users can currently export the conversion-history metadata/, "Privacy page must accurately disclose the implemented history CSV export");
assert.match(privacySource, /Signed-in users can also currently delete their saved conversion-history metadata/, "Privacy page must accurately disclose history deletion");
assert.doesNotMatch(privacySource, /There is currently no self-service account or conversion-history deletion control/, "Privacy page must not retain the obsolete no-deletion claim");
assert.doesNotMatch(privacySource, /Stripe/i, "Privacy page must not imply live Stripe/payment processing exists");

console.log("Freemium/product/privacy regression: PASS");
