import { nodeRequestToWebRequest } from "./usage.js";
import { getDb } from "./_lib/db.js";
import { getSessionUser, requireSameOrigin, randomToken, securityEvent, sha256 } from "./_lib/auth.js";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
type VercelRequest={method?:string;url?:string;headers:Record<string,string|string[]|undefined>;body?:unknown;[key:string]:unknown};
type VercelResponse={statusCode?:number;setHeader(name:string,value:string|string[]):VercelResponse;end(body?:string):void};
async function sendWebResponse(response:Response,res:VercelResponse):Promise<void>{res.statusCode=response.status;response.headers.forEach((value,name)=>res.setHeader(name,value));res.end(await response.text());}
async function handleApiKeysRequest(request:Request):Promise<Response>{const user=await getSessionUser(request);if(!user)return json({error:"Authentication required."},401);const sql=getDb();if(request.method==="GET"){const rows=await sql<any[]>`SELECT id,name,key_prefix,created_at,last_used_at,expires_at,revoked_at FROM api_keys WHERE user_id=${user.id} ORDER BY created_at DESC`;return json({keys:rows});}if(request.method!=="POST"&&request.method!=="DELETE")return json({error:"Method not allowed."},405);requireSameOrigin(request);if(request.method==="POST"){const input=await request.json().catch(()=>null) as {name?:unknown;expiresAt?:unknown}|null;const name=typeof input?.name==="string"?input.name.trim().slice(0,100):"";if(!name)return json({error:"A key name is required."},400);const [plan]=await sql<any[]>`SELECT p.api_access FROM users u JOIN plans p ON p.id=u.plan_id WHERE u.id=${user.id}`;if(!plan?.api_access&&user.role!=="admin")return json({error:"API access is not enabled for this plan."},403);const secret=`ps_live_${randomToken(32)}`;const hash=await sha256(secret);const prefix=secret.slice(0,16);const expiresAt=typeof input?.expiresAt==="string"?input.expiresAt:null;const [row]=await sql<any[]>`INSERT INTO api_keys (user_id,name,key_prefix,key_hash,expires_at) VALUES (${user.id},${name},${prefix},${hash},${expiresAt}) RETURNING id,name,key_prefix,created_at,expires_at`;await securityEvent(request,"api_key_created",user.id,{apiKeyId:row.id});return json({key:row,secret},201);}const input=await request.json().catch(()=>null) as {id?:unknown}|null;if(typeof input?.id!=="string")return json({error:"Key id is required."},400);const result=await sql<any[]>`UPDATE api_keys SET revoked_at=now() WHERE id=${input.id} AND user_id=${user.id} AND revoked_at IS NULL RETURNING id`;if(!result[0])return json({error:"Key not found."},404);await securityEvent(request,"api_key_revoked",user.id,{apiKeyId:input.id});return json({ok:true});}
export default async function handler(request:VercelRequest,response:VercelResponse):Promise<void>{await sendWebResponse(await handleApiKeysRequest(await nodeRequestToWebRequest(request)),response);}
